### ISSUE TITLE
switching set content is missing

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content#13]
Latest contents from https://dash.akamaized.net/WAVE/vectors/database.json missing switching set contents.
All of them has only one video representation cannot check the switching set tests.

**Comment by rbouqueau** [comment]
Please check t1 again and let me know. I haven't changed anything but the caching on the server is extremely agressive so you may have watched an older version without noticing.

**Comment by yanj-github** [comment]
Thanks @rbouqueau I am looking at https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t1/stream.mpd
Just want to make sure I understand it correctly. I can see 2 representation in t1. One is video one is audio. I think switching set need at more than one video representation isnt it?

**Comment by jpiesing** [comment]
>  I think switching set need at more than one video representation isnt it?

No. I believe a Switching Set can include one representation.

**Comment by andyburras** [comment]
`No. I believe a Switching Set can include one representation.`

Bit confused by that. The switching tests are driven by a playout array of representations, e.g.:

    "playout": [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 1, 1, 1, ... 1, 1],

so there needs to be at least 2 separate Representations?
