### ISSUE TITLE
Discrepancy between durations in database.json and tests.json

### ISSUE THREAD

**Issue by andyburras** [cta-wave/Test-Content#14]
There looks to be a discrepancy on the duration in some of the content. For e.g. http://dash.akamaized.net/WAVE/vectors/database.json gives:
```
"./output/avc_sets/15_30_60/t20": {
[...]
    "segmentDuration": "2",
    "fragmentType": "duration",
```

but the tests.json file gives:
```
        "54694ae36ab3a4e99db15dcfa41b6ab8": {
            "path": "avc/sequential-track-playback__stream__.html",
            "video": "https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t20/stream.mpd",
            "audio": "",
            "code": "sequential-track-playback.html",
            "config": {
                "fragment_duration": "PT0H0M2.021S",
[...]
```

It's possible that the "fragment_duration" is being taken from the MPD's maxSegmentDuration which is also "PT0H0M2.021S". But presumably segments may be less than this?

The Observation Framework relies on the fragment_duration being accurate for calculations in e.g.the random access tests. Currently these are generating failures with the latest content.

**Comment by rbouqueau** [comment]
Audio segments are chunked at access units boundaries. Access units have a duration of 1024/44100 seconds. Therefore audio segments are never 2s (which is the input request) but are on average 2s with a maximum of (2s*44100/1024) + 1 = 87 access units => 2.020136...s.

So taking the value from MPD@maxSegmentDuration is indeed probably not a good option.

**Comment by yanj-github** [comment]
@louaybassbouss  Can test runner pass actual segment duration in "tests.json" file instead of MPD@maxSegmentDuration which is PT0H0M2.021S please?

**Comment by yanj-github** [comment]
The new tests.json file looks fine now as it shows fragment_duration for each representation.
