### ISSUE TITLE
stop using Akamai for files that can change

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#15]
https://dash.akamaized.net/ has caching behaviour optimised for files that don't change. If files are changed then old data may be returned. Deleting files may take time to take effect.

database.json should be moved to github.
@nicholas-fr when new mezzanine content is uploaded, it should always have different filenames or (preferably) put in a different directory (e.g. including the upload date as a directory in the path)
@rbouqueau the same applies for new test content as for new mezzanine content
@louaybassbouss the scripts that read files from Akamai need to be modified once the file is moved to github

What files in addition to https://dash.akamaized.net/WAVE/vectors/database.json need to be moved to github?

**Comment by jpiesing** [comment]
Alternatively we we want to keep database.json on Akamai, we can include a version or date in the filename or path.

**Comment by nicholas-fr** [comment]
Good idea. Speaking for the mezzanine content, I propose the following:

For approved releases:
`WAVE/Mezzanine/<version_number>/`
e.g. 
`WAVE/Mezzanine/v1/`

For review content:
`WAVE/Mezzanine/new/<date>/`
e.g.
`WAVE/Mezzanine/new/20210608/`

**Comment by rbouqueau** [comment]
Call today (2021/06/08):
 - Mezzanine or any content that is not expected to change: use signature (e.g. md5) hosted on another server.
 - Test Content or any content that may evolve: use a unique path structure using either a version/date/random pattern. This content will be indexed from a file hosted on another server. This is a good opportunity to introduce a new path structure that includes other parameters e.g. spec version.

NB1: for Mezzanine we had a separate discussion so we need to articulate with [metadata](https://github.com/cta-wave/mezzanine/issues/29).
NB2: for "another server" github was proposed.

**Comment by andyburras** [comment]
I'm not sure if just creating new named directories for new content is going to solve all the cacheing problems. I'm finding I can got to e.g. https://dash.akamaized.net/WAVE/Mezzanine/new/20210608/ 
However, if I click on parentDirectory I see a listing of:

```
[DIR] Parent Directory                  01-Jan-1970 00:00      -  
[FILE] ad_bbb_AD-A1_1280x720@25_30.mp4   31-Mar-2021 13:42  42.1M  
[FILE] ad_bbb_AD-A1_1280x720@30_30.mp4   30-Mar-2021 14:51  42.4M  
[FILE] ad_bbb_AD-B1_1920x1080@25_30.mp4  31-Mar-2021 13:40  81.5M  
[FILE] ad_bbb_AD-B1_1920x1080@30_30.mp4  30-Mar-2021 14:55  82.8M  
[FILE] croatia_L1_1920x1080@25_60_2nd..> 01-Apr-2021 03:14   601M  
[FILE] croatia_L1_1920x1080@50_60_2nd..> 01-Apr-2021 03:41   717M  
[FILE] mezzanine[full-scale_white_noi..> 13-Apr-2021 12:32   5.5M  
[FILE] tos_L1_1920x1080@29.97_60_2ndA..> 22-Jan-2021 21:57   344M  
[FILE] tos_L1_1920x1080@30_60_2ndAudi..> 22-Jan-2021 21:04   347M  
[FILE] tos_L1_1920x1080@59.94_60_2ndA..> 22-Jan-2021 23:47   350M  
[FILE] tos_L1_1920x1080@60_60_2ndAudi..> 22-Jan-2021 22:52   356M  
```
The 20210608 directory is not listed. So it looks like the server may be cacheing the directory listings too?

**Comment by jpiesing** [comment]
> I'm not sure if just creating new named directories for new content is going to solve all the cacheing problems. I'm finding I can go to e.g. https://dash.akamaized.net/WAVE/Mezzanine/new/20210608/

I've also seen things in the past that suggest this. What breaks if directory listings are cached? Do we rely on reading directory listings anywhere?

**Comment by andyburras** [comment]
I think it means we need to ensure we have an up to date reference of what's available stored off the server, and make sure that is the point everyone references in documents etc., as Romain proposes for the Test Content with "This content will be indexed from a file hosted on another server".
(i.e. you can't just go to e.g. https://dash.akamaized.net/WAVE/Mezzanine/new and look at which is the latest content listed.)

**Comment by jpiesing** [comment]
I'm trying to understand what we need to do in order to move forwards. What have I missed in this proposal? What can be improved?

1) We decide the following;
- that database.json will be kept in github, e.g. in the top level of this repo - cta-wave / Test-Content
- that each upload of media (mezzanine or test content) will have the date in YYYY-MM-DD format as a directory in the path
2) @rbouqueau modifies the test content generation script to 1) work with database.json in the new location and 2) edit database.json to remove previous versions when new test content is being uploaded
3) @louaybassbouss modifies import.sh and download-content.py to get database.json from github and to provide a 2nd URL that is the base for the relative URLs in database.json.
4) Extend database.json to have an MD5sum (or similar) for each zip file and modify download-content.py to check this.

**Comment by nicholas-fr** [comment]
Based on Jon's proposal, for mezzanine specifically, I propose the following, to make the folder structure clearer.

Use the upload date in the path for new mezzanine content under review or old content scheduled for deletion:
https://dash.akamaized.net/WAVE/Mezzanine/under_review/YYYY-MM-DD/
https://dash.akamaized.net/WAVE/Mezzanine/to_be_deleted/YYYY-MM-DD/

Use the version number for approved mezzanine releases:
https://dash.akamaized.net/WAVE/Mezzanine/releases/v1/
...
https://dash.akamaized.net/WAVE/Mezzanine/releases/vN/


This structure can be mirrored in github where the JSON metadata files (with MD5) can be stored (or copied).
For releases:
https://github.com/cta-wave/mezzanine/metadata/releases/v1/*.json
For others:
https://github.com/cta-wave/mezzanine/metadata/under_review/YYYY-MM-DD/*.json
https://github.com/cta-wave/mezzanine/metadata/to_be_deleted/YYYY-MM-DD/*.json

**Comment by louaybassbouss** [comment]
database.json in GitHub has one more level as the one in Akamai. 

database.json in GitHub
```
{
  "CFHD": {
    "./output/avc_sets/15_30_60/t1": {
      "representations": [
        {...
```

database.json in Akamai
```
 {
  "./output/avc_sets/15_30_60/t1": {
    "representations": [
      {...
```

@rbouqueau  do you expect more changes in the JSON structure?

**Comment by louaybassbouss** [comment]
FYI download script is update to new github location and new database.json structure 

https://github.com/cta-wave/dpctf-deploy/issues/21#issuecomment-868320340

**Comment by rbouqueau** [comment]
> @rbouqueau do you expect more changes in the JSON structure?

Sorry if the change looked unintended. And thanks for providing a way to signal updates.

I received no formal requirements. So if the format is ok for you it should remain stable. At least should extend safely to new framerates.

I'm unsure about hevc, audio, other encryption schemes, ad-insertion... Is there a requirement here 1) to have one format for all and 2) to display them from the same page? I certainly need more visibility to make better choices.

**Comment by louaybassbouss** [comment]
Thanks a lot @rbouqueau  the script now supports the latest version of the database.json. the most important parameters for us are `zipPath` and `mpdPath` and their location in the JSON. Anything else can updated  without affecting the download script.

**Comment by jpiesing** [comment]
@rbouqueau @louaybassbouss What needs to be done so we can close this issue for the test content? Is there anything left to address?
@nicholas-fr What is left for the mezzanine content? If that's significant, would it be better to open a separate issue in the mezzanine content project?

**Comment by rbouqueau** [comment]
On my side the issue is fixed.

**Comment by louaybassbouss** [comment]
> On my side the issue is fixed.

Same for me

**Comment by nicholas-fr** [comment]
The mezzanine files on the Akamai server have been moved to adopt the agreed naming.

New mezzanine content under review or old content scheduled for deletion:
https://dash.akamaized.net/WAVE/Mezzanine/under_review/YYYY-MM-DD/
https://dash.akamaized.net/WAVE/Mezzanine/to_be_deleted/YYYY-MM-DD/

Approved mezzanine releases:
https://dash.akamaized.net/WAVE/Mezzanine/releases/1/

I've created an [issue](https://github.com/cta-wave/mezzanine/issues/38) to track the remaining action related to mezzanine  content.

**Comment by jpiesing** [comment]
> I've created an [issue](https://github.com/cta-wave/mezzanine/issues/38) to track the remaining action related to mezzanine content.

Nothing left here so closing.
