### ISSUE TITLE
regenerate 15-30-60 test content

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#16]
@rbouqueau When it's convenient, please can you regenerate the 15-30-60 test content based on the new mezzanine content from https://github.com/cta-wave/mezzanine/issues/35?

I appreciate you may want to wait until a few other changes have landed & that's fine.

**Comment by rbouqueau** [comment]
@jpiesing I'm assuming you mean cta-wave/mezzanine#35 (and not cta-wave/device-playback-task-force#89). Let me know otherwise.

I plan to process it in the next business days.

**Comment by jpiesing** [comment]
> @jpiesing I'm assuming you mean [cta-wave/mezzanine#35](https://github.com/cta-wave/mezzanine/issues/35) (and not [cta-wave/device-playback-task-force#89](https://github.com/cta-wave/device-playback-task-force/issues/89)). Let me know otherwise.

Yes. Sorry. I've edited the original issue to avoid confusing the next person to look at this.

> I plan to process it in the next business days.

Good. Thanks.

**Comment by rbouqueau** [comment]
- updated mezzanine
- changed copyrights
- uploaded to a different folder (prefixed with date): https://dash.akamaized.net/WAVE/vectors/2021-06-11
- index accessible from this codebase
- update README: see below to update the Web access URL

@jpiesing @haudiobe or whomever is the admin: could you please activate the "github pages" feature on this repository? Or give me some admin rights to do so. I'd like to put the code of the index directly here, it would be more convenient for updates.

**Comment by jpiesing** [comment]
> @jpiesing @haudiobe or whomever is the admin: could you please activate the "github pages" feature on this repository? Or give me some admin rights to do so. I'd like to put the code of the index directly here, it would be more convenient for updates.

@cta-source Do you have sufficient admin rights to do this?

**Comment by cta-source** [comment]
I do, and it should be up now at https://cta-wave.github.io/Test-Content/

Mike Bergman

**Comment by rbouqueau** [comment]
Excellent, thanks!
