### ISSUE TITLE
Migrate to Database

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/Test-Content#2]
The content hosting should be migrated to a database similar to what DASH-IF has done - https://testassets.dashif.org. This is some effort, first estimates are around 5 days. Also some maintenance of this work is important.

**Comment by rbouqueau** [comment]
@haudiobe I think that's what we have: https://github.com/cta-wave/Test-Content/blob/master/database.json

If yes, please close this issue. If not please provide additional details! Thanks

**Comment by haudiobe** [comment]
This seems to solve the issue of reading from a consistent data base. However, writing to the data base is done manually and error prone. In DASH-IF, this is done through a data base and makes it much more robust. Moving the test content to a data base may still be beneficial. The one being the "owner" of the data base should decide on this.

**Comment by gitwjr** [comment]
@haudiobe @rbouqueau 
On the 11/8/22 call it was decided that one or both of you need to review this and determine if it can be closed or, if not, what needs to be done to close.

**Comment by rbouqueau** [comment]
For me the JSON seems sufficient. I agree with Thomas' previous comment that its manipulation is error prone. Merges should be done via pull requests with reviewers.
