### ISSUE TITLE
test contents splice_ad_bbb_* is missing

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content#20]
I don't see the test contents for splice_ad_bbb_* from the current content pool.
Can anyone generate them please?

**Comment by jpiesing** [comment]
> Is this related to #19 somehow?

They may be the same thing but #19 isn't specific about which content is actually needed and I'm not sure if all of the splice_ad_bbb_* are needed.

**Comment by yanj-github** [comment]
Sorry @rbouqueau didnt know already created. 
Can I closed this issue becuase this is duplicated now?

**Comment by rbouqueau** [comment]
Yes sure, you are the reporter :)
I haven't investigated the subject yet but both issues were opened in a closed time frame so I suspected they might be duplicates.

**Comment by yanj-github** [comment]
Duplicated to #19 closing it now.
