### ISSUE TITLE
zip folder strcuture isn't correct on 2021-09-29 folder

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content#22]
https://dash.akamaized.net/WAVE/vectors/2021-09-29/ folder contains eac3 an ac4 streams.
The zip should follow certain folder strcutal in order to read from TR.

ref: https://github.com/cta-wave/dpctf-tests/issues/66#issuecomment-968846199

**Comment by yanj-github** [comment]
@rbouqueau If I zip the current streams and send to you in email will you be able to help to upload to the same location in akamai server please?

**Comment by yanj-github** [comment]
Thanks @rbouqueau it means that we need to change the database.json as well. Which I will manualy update then create pull request after content uploaded on new url.  
In terms of replicaing the whole folder what do you need from me please? 
Sorry if I have missed but, do we have the folder structual documented anywhere so that I can follow please? As it has to be done carefully, I want to avoid any rework.

**Comment by rbouqueau** [comment]
> In terms of replicaing the whole folder what do you need from me please?

I can make the move the content for you. Just let me know.

> Sorry if I have missed but, do we have the folder structual documented anywhere so that I can follow please? As it has to be done carefully, I want to avoid any rework.

Not decided yet, see https://github.com/cta-wave/dpctf-tests/issues/59 for the on-going discussion. In the meantime we stick to the existing folder structure.

**Comment by yanj-github** [comment]
Thanks @rbouqueau I will email you the folder with correct zip file when it ready.

**Comment by abdulwahabEDT** [comment]
The database.json is updated with the paths to ac4 and eac3 content. @rbouqueau can you please review the pull request https://github.com/cta-wave/Test-Content/pulls and merge if everything is fine. thanks

**Comment by rbouqueau** [comment]
Merged. @reporter: Please close if ok now.
