### ISSUE TITLE
What audio test streams are needed for each codec?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#24]
With development of audio test streams starting or in progress for all the main codecs, we need a more organised approach to determining which audio streams are needed for each codec.

IMHO there are 2-3 sets of test streams needed for each audio codecs.
1. Streams for each bitstream option that is not tested by the standard (mandatory) device test suites - there may not be any of these. These streams are used with test 8.2 Sequential Track Playback. Does the stream play at all?
2. Streams for each option for how bitstreams are packaged in ISOBMFF/CMAF (e.g. initialisation segments, segment durations, packing audio 'segments' into CMAF chunks, edit lists?, ....). These streams are mostly used with test 8.2 Sequential Track Playback. Does the stream play at all?
3. Streams for specific tests. Many tests can re-use one of the streams from 8.2 Sequential Track Playback but there are exceptions.

The bitstream options and the ISOBMFF/CMAF options for each audio codec should be listed in an issue here. Ideally these would just be a list of references to sections in the bitstream spec and/or the CMAF binding spec.

**Comment by gitwjr** [comment]
Closed. Per Mike Bergman: "This one kicked off #26, which is where the focus is. Close this Issue and look to #26 (note also #25 and #27 were opened by #24 but are now closed). See https://github.com/cta-wave/Test-Content/issues/26".
