### ISSUE TITLE
Dolby audio codec options to be tested

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#25]
As explained in https://github.com/cta-wave/Test-Content/issues/24, one input into deciding which test streams are needed for a codec is the content options.
1. Streams for each bitstream option that is not tested by the standard (mandatory) device test suites - there may not be any of these. These streams are used with test 8.2 Sequential Track Playback. Does the stream play at all?
2. Streams for each option for how bitstreams are packaged in ISOBMFF/CMAF (e.g. initialisation segments, segment durations, packing audio 'segments' into CMAF chunks, edit lists?, ....). These streams are mostly used with test 8.2 Sequential Track Playback. Does the stream play at all?

The bitstream options and the ISOBMFF/CMAF options for each Dolby audio codec covered by the work at Eurofins should be listed in this issue. Ideally these would just be a list of references to sections in the bitstream spec and/or the CMAF binding spec.

**Comment by jpiesing** [comment]
@andyburras @yanj-github please can one of you assign this to someone familiar enough with the Dolby audio codecs. If this is someone from Eurofins, please also mention someone from Dolby familiar with this work.

**Comment by JanMueDlb** [comment]
I can help with defining the necessary content options for the Dolby formats.

**Comment by JanMueDlb** [comment]
Attached the update to the specification (v1.10) that includes now the latest additions for DTS-HD, E-AC-3 and AC-4 (based on the shared AAC additions). 

[dpctf-s00001-v032-WAVE-DPC-v1.10_update_for_AAC_AC4_DTS.docx](https://github.com/cta-wave/Test-Content/files/7881198/dpctf-s00001-v032-WAVE-DPC-v1.10_update_for_AAC_AC4_DTS.docx)

**Comment by JanMueDlb** [comment]
We have an update for the DPCTF specification that includes the plain stereo content option (unencrypted) in https://github.com/cta-wave/device-playback-task-force/issues/39

This is for review now and would be the highest priority for Dolby codec options to be tested.

**Comment by JanMueDlb** [comment]
test codec excel sheet for AC-4 and E-AC-3

[WAVE.test.content.test.code.Matrix-Dolby.xlsx](https://github.com/cta-wave/Test-Content/files/9131177/WAVE.test.content.test.code.Matrix-Dolby.xlsx)

**Comment by pmaness** [comment]
test codec excel sheet adding dts and LBR
[WAVE.test.content.test.code.Matrix-DTS.xlsx](https://github.com/cta-wave/Test-Content/files/9172071/WAVE.test.content.test.code.Matrix-DTS.xlsx)

**Comment by andyburras** [comment]
Jan has uploaded the spreadsheet detailing the Dolby content options being tested, so I think we can close this now.
