### ISSUE TITLE
DTS audio codec options to be tested

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#26]
As explained in https://github.com/cta-wave/Test-Content/issues/24, one input into deciding which test streams are needed for a codec is the content options.
1. Streams for each bitstream option that is not tested by the standard (mandatory) device test suites - there may not be any of these. These streams are used with test 8.2 Sequential Track Playback. Does the stream play at all?
2. Streams for each option for how bitstreams are packaged in ISOBMFF/CMAF (e.g. initialisation segments, segment durations, packing audio 'segments' into CMAF chunks, edit lists?, ....). These streams are mostly used with test 8.2 Sequential Track Playback. Does the stream play at all?

The bitstream options and the ISOBMFF/CMAF options for each DTS audio codec covered by the work at GPAC licensing should be listed in this issue. Ideally these would just be a list of references to sections in the bitstream spec and/or the CMAF binding spec.

**Comment by jpiesing** [comment]
@pmaness

**Comment by JanMueDlb** [comment]
updates to the specification for DTS-HD can be found in #25

**Comment by pmaness** [comment]
Adding DTS core and LBR to the spreadsheet:
[WAVE.test.content.test.code.Matrix-DTS.xlsx](https://github.com/cta-wave/Test-Content/files/9172080/WAVE.test.content.test.code.Matrix-DTS.xlsx)

**Comment by pmaness** [comment]
I provided an updated spreadsheet indicating tests for the DTS codecs (see comment above from July 22). I'm not clear what else is being requested.

**Comment by rbouqueau** [comment]
This issue is assigned to me. Could we check the status?

**Comment by rbouqueau** [comment]
It seems to me that this is done. Can you check and close?

**Comment by pmaness** [comment]
I agree. I think it's closed now

**Comment by gitwjr** [comment]
Closed per @pmaness pmaness
