### ISSUE TITLE
MPEG audio codec options to be tested

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#27]
As explained in #24, one input into deciding which test streams are needed for a codec is the content options.
1. Streams for each bitstream option that is not tested by the standard (mandatory) device test suites - there may not be any of these. These streams are used with test 8.2 Sequential Track Playback. Does the stream play at all?
 2. Streams for each option for how bitstreams are packaged in ISOBMFF/CMAF (e.g. initialisation segments, segment durations, packing audio 'segments' into CMAF chunks, edit lists?, ....). These streams are mostly used with test 8.2 Sequential Track Playback. Does the stream play at all?

The bitstream options and the ISOBMFF/CMAF options for each MPEG audio codec covered by the work at Eurofins should be listed in this issue. Ideally these would just be a list of references to sections in the bitstream spec and/or the CMAF binding spec.

**Comment by jpiesing** [comment]
@andyburras @yanj-github Please can you assign this to someone familiar with the MPEG audio codecs that are in scope for your work. If that is someone from Eurofins, please also mention someone from Fraunhofer who is familiar with this work.

**Comment by yanj-github** [comment]
@jpiesing please assign this to myself. I will be liaising with Ingo from Fraunhofer IIS to work on this.

**Comment by yanj-github** [comment]
[WAVE test content _ test code sparse Matrix - AAC.xlsx](https://github.com/cta-wave/Test-Content/files/7713460/WAVE.test.content._.test.code.sparse.Matrix.-.AAC.xlsx)

TODO: streams for splicing tests

**Comment by yanj-github** [comment]
As discussed on 12/01/22 DPCTF meeting:
Once this list is approved its need to be documented somewhere and the link of it to be included in the spec. 
Where is the best place to document it?
Currently we have https://github.com/cta-wave/Test-Content-Generation/wiki/CAAC-Test-Streams.

**Comment by jpiesing** [comment]
> [WAVE test content _ test code sparse Matrix - AAC.xlsx](https://github.com/cta-wave/Test-Content/files/7713460/WAVE.test.content._.test.code.sparse.Matrix.-.AAC.xlsx)
> 
> TODO: streams for splicing tests

I don't have any audio expertise so cannot comment on the set of options (A2-A14) but ....
I notice that the options for drc, PCE, Bitrate & Sample Rate never change from what's in the baseline.
I remember the discussion about testing Sample Rate of 48kHz.
I can't see any point in testing different bitrates (although there's a typo - 128kHz should be 128 kbit/sec I think).
Can someone who knows more than me confirm it's OK to only test drc absent & PCE absent?

**Comment by jpiesing** [comment]
February 1st meeting
Discussion about drc and PCE.
Similar to the proposal for Dolby codecs except that proposal omits rows 6/7/8/9. Edit list is assumed to always be present. DRC and PCE are omitted.
2 errors cmfc change to cmf2, kHz on bitrate needs to be kbits/sec.

Conclusion: 
Eurofins to upload a new version of the document. 
As approved as it's going to be.

**Comment by yanj-github** [comment]
[WAVE.test.content.test.code.sparse.Matrix-AAC-approved.xlsx](https://github.com/cta-wave/Test-Content/files/7980332/WAVE.test.content.test.code.sparse.Matrix-AAC-approved.xlsx)

**Comment by jpiesing** [comment]
Closing as requested.

**Comment by jpiesing** [comment]
@yanj-github What duration is needed for the text content? 20s? 30s? 60s? Do some tests need 60s but 20s/30s would be suitable for others?

**Comment by yanj-github** [comment]
Hi @jpiesing  as duration will require further discussion and we have issue to capture the duration discussion already which is https://github.com/cta-wave/dpctf-tests/issues/56.
Instead keeping the AAC stream generataion blocked, can we close this issue and go for 60s duration for now until the duration of tests are get agreed please?

**Comment by yanj-github** [comment]
We have started to generate audio streams of 60s duration for now. 
Any changes requuied to have shorter duration. will be captured on issue https://github.com/cta-wave/dpctf-tests/issues/56.
@jpiesing Can we close this ticket for now please?

**Comment by jpiesing** [comment]
OK.
