### ISSUE TITLE
Wrong paths and ZIP structure

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/Test-Content#30]
The current database.json has MPD and ZIP paths with an additional date in them. The same is the case for the ZIP file structure:

Current:
```
https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/2022-01-17/stream.mpd
https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/2022-01-17/t1.zip
/avc_sets/12.5_25_50/t1/2022-01-17/stream.mpd
```

Correct:
```
https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/stream.mpd
https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1.zip
/avc_sets/12.5_25_50/t1/stream.mpd
```

**Comment by yanj-github** [comment]
I think the current strcuture matches what is has been agreed on https://github.com/cta-wave/dpctf-tests/issues/59
"https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/stream.mpd" this will cause problem when there muiltple release to same streams.

**Comment by rbouqueau** [comment]
I agree with @yanj-github .

**Comment by jpiesing** [comment]
> I think the current strcuture matches what is has been agreed on [cta-wave/dpctf-tests#59](https://github.com/cta-wave/dpctf-tests/issues/59)
> "https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/stream.mpd" this will cause problem when there muiltple release to same streams.

We agreed to include the dates in the paths in order to be able to upload new versions of the same content. As has been discussed before, the Akamai server doesn't handle updating files very well due to caching.

**Comment by louaybassbouss** [comment]
@FritzHeiden  We already use the CDN URLs with the date in the URL path since months and it is working fine.  This is what [changed in the database.json](https://github.com/cta-wave/Test-Content/commit/fa31d46e0f8cedf0636dbb09d3be5f83e0a9200c) in the last commit (also in screenshot). The position of the date in the URL path is moved which should be fine for us, but the ID (in the example below from `avc_sets/12.5_25_50/t1` to `avc_sets/12.5_25_50/t1/2022-01-17/`) is changed and this causes the issue on our side. We use this ID for creating the filenames.  @rbouqueau can you change ID to the previous structure?

![image](https://user-images.githubusercontent.com/1138409/154437774-66f54cd4-84cd-4acd-97e4-1522a51ae15f.png)

**Comment by jpiesing** [comment]
> @FritzHeiden We already use the CDN URLs with the date in the URL path since months and it is working fine. This is what [changed in the database.json](https://github.com/cta-wave/Test-Content/commit/fa31d46e0f8cedf0636dbb09d3be5f83e0a9200c) in the last commit (also in screenshot). The position of the date in the URL path is moved which should be fine for us, but the ID (in the example below from `avc_sets/12.5_25_50/t1` to `avc_sets/12.5_25_50/t1/2022-01-17/`) is changed and this causes the issue on our side. We use this ID for creating the filenames. @rbouqueau can you change ID to the previous structure?

moving the date to be after "avc_sets/12.5_25_50" was agreed in the issue referenced above so that updates to "avc_sets/12.5_25_50" are still under ""avc_sets/12.5_25_50".

**Comment by rbouqueau** [comment]
@jpiesing Louay's request to remove the date from the ID seems reasonable. Any objection on me implementing this?

@jpiesing  Fritz's request to remove the date from the archive is debatable (and above all happens too late since the implementation of #59 is done and external contributors like Eurofins have already submitted content). I understand the rationale though. I'm looking for additional feedback as either me or Fritz will have to do some work anyway.

**Comment by jpiesing** [comment]
> @jpiesing Louay's request to remove the date from the ID seems reasonable. Any objection on me implementing this?

No. This also means that updated content would be picked up on automatically.

> @jpiesing Fritz's request to remove the date from the archive is debatable (and above all happens too late since the implementation of #59 is done and external contributors like Eurofins have already submitted content). I understand the rationale though. I'm looking for additional feedback as either me or Fritz will have to do some work anyway.

Now I'm confused. We made an intentional decision to move the date in the path to the MPD and media segments to the end.

**Comment by louaybassbouss** [comment]
> > @jpiesing Louay's request to remove the date from the ID seems reasonable. Any objection on me implementing this?
> 
> No. This also means that updated content would be picked up on automatically.

@jpiesing regardless if the ID includes a date or not, we will not use this date in the filename of the generated test e.g. `sequential-track-playback__t1.html`.  @rbouqueau  you can then keep the date in the ID and we update the generate script to only consider the content name e.g. `t1` in the case of `sequential-track-playback__t1.html`. 

> > @jpiesing Fritz's request to remove the date from the archive is debatable (and above all happens too late since the implementation of #59 is done and external contributors like Eurofins have already submitted content). I understand the rationale though. I'm looking for additional feedback as either me or Fritz will have to do some work anyway.
> 
> Now I'm confused. We made an intentional decision to move the date in the path to the MPD and media segments to the end.

@jpiesing  @rbouqueau  the structure is fine for us no need to change anything on your side and this agree in issue https://github.com/cta-wave/dpctf-tests/issues/59.

**Comment by rbouqueau** [comment]
Ok, closing then.

**Comment by cta-source** [comment]
Where is the structure documented? It seems like this debate should be resolved by, “Let’s review the spec for ID strings.”

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402

**Comment by cta-source** [comment]
I'm not the right person to answer that. @haudiobe and @jpiesing, we need to keep documenting these details, is the DPCTF spec Annex A (test content annotations and related details) the correct place?
