### ISSUE TITLE
Wrong structure for CEAC Test Content

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/Test-Content#32]
@yanj-github  the structure of the CEAC Test Content in database.json ( See https://github.com/cta-wave/Test-Content/blob/master/database.json#L1719) is not following the structure described in https://github.com/cta-wave/dpctf-tests/issues/59 . Can you check it please?

**Comment by yanj-github** [comment]
Hi @louaybassbouss  Thanks for reporting we are aware of this. Can you let us know if this is a blocker on your end please?

**Comment by louaybassbouss** [comment]
> Hi @louaybassbouss Thanks for reporting we are aware of this. Can you let us know if this is a blocker on your end please?

@yanj-github  it is possible to update first the IDs of the of the items? We use these IDs to generate the filenames. You can update the MPD/ZIP paths later.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss  for the confirmation. As the path of MPD/ZIP not a blocker to you we are planning to correct this later. Thanks

**Comment by yanj-github** [comment]
The correction of IDs are fixed and merged now.

**Comment by louaybassbouss** [comment]
Thanks @yanj-github LGTM closing this issue
