### ISSUE TITLE
25Hz Test Content labeled with 15_30_60 in database.json

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/Test-Content#35]
The 25Hz Splicing Test Content in database.json (e.g. https://github.com/cta-wave/Test-Content/blob/master/database.json#L1646 ) is labeled with `.../15_30_60/...` (JSON IDs, zipPath, mpdPath). @rbouqueau can you check it please.

**Comment by rbouqueau** [comment]
Thanks @louaybassbouss , should be fixed. I let you close if ok.

**Comment by louaybassbouss** [comment]
Thanks @rbouqueau closing this issue.
