### ISSUE TITLE
AAC test streams to front page

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/Test-Content#36]
The AAC streams were added to the data base but are not visible on the front page. What needs to be done to make this happen?

**Comment by rbouqueau** [comment]
Done!

**Comment by yanj-github** [comment]
@rbouqueau I can see CAAC tab but links for eac3 streams are listed.

**Comment by rbouqueau** [comment]
That's correct and I can see the source of this confusion: the JS script accesses the elements by index, not by name. Let me dig into this when I find some time.

**Comment by rbouqueau** [comment]
Should be addressed. Please close if ok.

I've noticed that there are other root elements (CEAC, CE4S, ...). Let me know if you wish to add them.

**Comment by yanj-github** [comment]
Yes please @rbouqueau it would be nice to show (CEAC, CE4S) as well, thanks.

**Comment by rbouqueau** [comment]
Done.

**Comment by yanj-github** [comment]
It looks fine to me.
Do we need to raise issue to update the link later when the streams updated?

**Comment by rbouqueau** [comment]
The group proposed to make pull requests in this case. Let me know if you see any limitation to this approach, otherwise please close the issue.

**Comment by yanj-github** [comment]
@rbouqueau Thanks.  I dont have permission to close the issue.

**Comment by jpiesing** [comment]
> @rbouqueau Thanks. I dont have permission to close the issue.

Closing as agreed.
