### ISSUE TITLE
databse.json example not up-to-date on readme

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content#37]
https://github.com/cta-wave/Test-Content#how-does-this-site-work Here we have an example of database.json file and how the entries should look like. But, it seems not up to date to the latest folder structure etc.
Is the database.json standard documented elsewhere in case I have missed anything.

**Comment by rbouqueau** [comment]
I propose to remove the example. Would that work for you? I think the JSON is simple enough to be considered self-documented.

**Comment by yanj-github** [comment]
ok
