### ISSUE TITLE
Incorrect QR code content

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/Test-Content#45]
Unable to validate the tests in the following group:

```
cfhd_15_30_60-local/
sequential-track-playback__t21.html
sequential-track-playback__t22.html
sequential-track-playback__t24.html
sequential-track-playback__t26.html
sequential-track-playback__t27.html
sequential-track-playback__t28.html
sequential-track-playback__t29.html
sequential-track-playback__t30.html
sequential-track-playback__t31.html
sequential-track-playback__t32.html
sequential-track-playback__t33.html
```

This is due to the QR code content showing “60 seconds” instead of “1 minute” 

The latest mezzanine release ([v3](https://dash-large-files.akamaized.net/WAVE/Mezzanine/releases/3/)) has been checked (by Nicholas Frame) and the mezzanine content has the correct QR codes, indicating the wrong mezzanine has been used.

For further details on the issue please see:
[Eurofins CTA WAVE Test Suite validation of the Observation Framework results including analysis 31 Jan 2023.xls](https://standards.cta.tech/apps/org/workgroup/dpctf/document.php?document_id=37957)

**Comment by rbouqueau** [comment]
Content updated.

**Comment by gitwjr** [comment]
This was fixed per Romain. Close.
