### ISSUE TITLE
Front-end consistency discussion and update

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/Test-Content#48]
See discussion in https://github.com/cta-wave/Test-Content/issues/41#issuecomment-1557560923

The overall status of the front-end needs a review. Are there people using it? If so how do these people plan to use it?

The existing HEVC stream (CHH1) is not listed. Neither is CHDF. SS1 is in the CFHD tab... which makes it unclear to me whether "chunked" also belong to CFHD or to its own tab.

I could propose to create one tab for each of these: CHH1, CHDF, SS1, chunked.

Opinion?

**Comment by jpiesing** [comment]
> See discussion in [#41 (comment)](https://github.com/cta-wave/Test-Content/issues/41#issuecomment-1557560923)
> 
> The overall status of the front-end needs a review. Are there people using it? If so how do these people plan to use it?
> 

Ideally the front end would keep some statistics about its use :)

> The existing HEVC stream (CHH1) is not listed. Neither is CHDF. SS1 is in the CFHD tab... which makes it unclear to me whether "chunked" also belong to CFHD or to its own tab.
> 
> I could propose to create one tab for each of these: CHH1, CHDF, SS1, chunked.
> 

I would be inclined to simplify the number of tabs and have one per codec. One per media profile might also make some sense but then the AVC 4.2 would be on its own which is silly.

> Opinion?

**Comment by rbouqueau** [comment]
> Ideally the front end would keep some statistics about its use :)

https://github.com/cta-wave/Test-Content/graphs/traffic

**Comment by rbouqueau** [comment]
My last comment is wrong (this is for the traffic of the repository on github). I couldn't find any way to get this information from github. Should we install a tool on the Website then? Which tool does CTA usually use?
