### ISSUE TITLE
2023-09-01 content wrong dates in ss1 MPDs

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/Test-Content#53]
The referenced content in the SS1 content MPDs still has 2023-04-28 in the path of the referenced content

From https://dash.akamaized.net/WAVE/vectors/switching_sets/12.5_25_50/ss1/2023-09-01/stream.mpd:

![image](https://github.com/cta-wave/Test-Content/assets/9076000/3af3c168-c994-4840-ae6f-42e87c3e1ec9)

**Comment by rbouqueau** [comment]
Thanks for reporting. I'm going to automatize the update from the script. This is definitely too error-prone.

**Comment by jpiesing** [comment]
@FritzHeiden Does this mean we don't have any recordings from the plugfest / test event that are usable for these 7 tests?

cfhd_12.5_25_50-local-fullscreen-playback-of-switching-sets__ss1_time_diff.csv
cfhd_12.5_25_50-local-overlapping-fragments__ss1_time_diff.csv
cfhd_12.5_25_50-local-playback-over-wave-baseline-splice-constraints__splice_main_splice_ad_time_diff.csv
cfhd_12.5_25_50-local-restricted-splicing-of-encrypted-content-https__splice_main-cenc_splice_ad-cenc_time_diff.csv
cfhd_12.5_25_50-local-sequential-playback-of-encrypted-and-non-encrypted-baseline-content-https__splice_main-cenc_splice_ad_time_diff.csv
cfhd_12.5_25_50-local-switching-set-playback__ss1-1_time_diff.csv
cfhd_12.5_25_50-local-switching-set-playback__ss1-2_time_diff.csv


Jon

**Comment by FritzHeiden** [comment]
> @FritzHeiden Does this mean we don't have any recordings from the plugfest / test event that are usable for these 7 tests?

Martin is using a workaround for this, so this shouldn't affect the recordings

**Comment by FritzHeiden** [comment]
I checked the updated database.json and it looks good now. 

Another thing I noticed however is the change in audio content. It seems like eac3_sets and ac4_sets is missing. I don't know how to deal with this change, is there an up to date matrix of test templates and audio content like there is for video?

**Comment by jpiesing** [comment]
> Another thing I noticed however is the change in audio content. It seems like eac3_sets and ac4_sets is missing. I don't know how to deal with this change, is there an up to date matrix of test templates and audio content like there is for video?

@yanj-github Can you help about audio content?

**Comment by yanj-github** [comment]
> > Another thing I noticed however is the change in audio content. It seems like eac3_sets and ac4_sets is missing. I don't know how to deal with this change, is there an up to date matrix of test templates and audio content like there is for video?
> 
> @yanj-github Can you help about audio content?

Hi Jon, the audio test will be coming soon. It is in progress on our end for Dolby test generation and some new test for aac chunked test and splicing test.

**Comment by jpiesing** [comment]
> I still don't know how to handle the issues with missing audio content in the new database json. As this only affects audio-only tests, should I just not include these when generating the tests?

Can you be more precise about which audio content you think is missing? There may be a misunderstanding.

**Comment by yanj-github** [comment]
@FritzHeiden I just made a pull request for audio only tests.
https://github.com/cta-wave/dpctf-tests/pull/123

-     Dolby tests regenerated using latest test content 2023-08-01 (2023-10-13 for eac3 at1)
-     AAC chunked tests added
-     AAC splicing tests added

**Comment by FritzHeiden** [comment]
Thanks @yanj-github for the PRs. I reviewed, tested and merged them. Content looks good now, closing.
