### ISSUE TITLE
Chunked content not playing

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/Test-Content#57]
I have problems playing the chunked content [1] in tests. Tried to find the issue in the player logic, however, to me it seems more like an issue with the content. All 5 chunks per segment are loaded into the buffer, first few frame are displayed, then playback stops in waiting state. After some investigation I could see there are numerous buffered ranges that are not continuous. 
As chunked content is not supported by dash reference player, I am unable to check the content there.

[1] https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/chunked/2023-09-01/stream.mpd

**Comment by jpiesing** [comment]
@FritzHeiden Can you provide any more detail on the gaps in the buffered ranges? Also I'm a little confused as I thought this worked correctly on the TVs in the HbbTV plugfests? If I look at cfhd_12.5_25_50-local/regular-playback-of-chunked-content__chunked.html in the 20231010 recording, I can't see anything wrong. Am I missing something?
