### ISSUE TITLE
chdf (1080p50/1080p60) content missing from https://cta-wave.github.io/Test-Content/

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#59]
There no mention of chdf (1080p50/1080p60) on https://cta-wave.github.io/Test-Content/.
Stream t20 is chdf - it's correctly missing from the cfhd tab but there's no chfd tab.

**Comment by rbouqueau** [comment]
Done.

Note that we already discussed about refactoring the tabs: https://github.com/cta-wave/Test-Content/issues/48#issuecomment-1557670976. I don't think we came to a clear conclusion.

I was eventually said that Fraunhofer relied on the [json database](https://cta-wave.github.io/Test-Content/database.json). So the front-end was not so important.

**Comment by jpiesing** [comment]
Confirmed.
