### ISSUE TITLE
Index not working (no content listed)

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content#7]
The index page does not seem to be working, as none of the content is listed.

![image](https://user-images.githubusercontent.com/9865551/101540846-e38ab100-39a0-11eb-9e23-be6855c4d48b.png)

**Comment by rbouqueau** [comment]
I think that was answered by Will Law in an email. Short answer: use http://dash.akamaized.net/WAVE/index.html?cache=clear.

Longer version:
> if you don’t supply the query arg, then it will give you the cached version. Bypassing the cache with the query arg does not then pull that object in to cache ;(
> 
> The account you are using is [a] test asset storage account, It is designed for very high volume delivery of video assets that don’t change very often (like test assets)

Does that solve the issue?

**Comment by nicholas-fr** [comment]
I'm afraid I didn't see that email, but thanks! This indeed resolves the issue.
I propose that the `README.md` be updated accordingly.

**Comment by jpiesing** [comment]
Indeed the link in the README.md needs updating.

**Comment by rbouqueau** [comment]
I've created a PR on this, you can merge if that's your wish. Please note that updating the README.md doesn't solve the core issue about the content itself that is still fetched on the cache.

**Comment by jpiesing** [comment]
> I've created a PR on this, you can merge if that's your wish. Please note that updating the README.md doesn't solve the core issue about the content itself that is still fetched on the cache.

I don't know who has the ability to approve the PR. @haudiobe ?

We are doing some promotion of this work so having confusing URLs in README.md really doesn't help.

**Comment by jpiesing** [comment]
I approved the PR but it's still not working.

**Comment by rbouqueau** [comment]
@jpiesing The URL for the webpage served by github is https://cta-wave.github.io/Test-Content/. Does it work for you? Is there anything we need to update?

**Comment by jpiesing** [comment]
I must have been using the old URL at the start of this issue. Closed.
