### ISSUE TITLE
downloading a CMAF track in one operation

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content#9]
See https://github.com/cta-wave/Test-Content-Generation/issues/19 concerning downloading all the segments from a CMAF track in a single operation.

As well as the test runner / test harness downloading all the media segments for a CMAF track in one operation, IMHO users should be able to download this from the test content UI as well.

**Comment by jpiesing** [comment]
@louaybassbouss I believe this is addressed with the .zip file for each switching set. If you agree, please close this issue.

**Comment by louaybassbouss** [comment]
Agree
